name: Build and Deploy to GCR

on:
  push:
    branches:
    - develop

# Environment variables available to all jobs and steps in this workflow
env:
  GCR_PROJECT: ${{ secrets.GCR_PROJECT }}
  GCR_EMAIL: ${{ secrets.GCR_EMAIL }}
  GCR_ZONE: europe-west1
  GCR_SERVICE: over-backend
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: over-backend
  REGISTRY_HOSTNAME: eu.gcr.io

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '281.0.0'
        service_account_email: ${{ secrets.GCR_EMAIL }}
        service_account_key: ${{ secrets.GCR_KEY }}

     #Configure gcloud CLI
    - name: gcloud Set up
      run: |
        gcloud config set project $GCR_PROJECT

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Replace tokens with secrets
    - name: Token replace
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '@@'
        tokenSuffix: '@@'
        files: '["**/*.modele"]'
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    # Write token
    - name: Token write
      run: |
        mv .env.modele .env

    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$REGISTRY_HOSTNAME"/"$GCR_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push $REGISTRY_HOSTNAME/$GCR_PROJECT/$IMAGE:$GITHUB_SHA

    # Activate beta commands
    - name: Activate cloud run cli
      run: |
        gcloud components install beta &&
        gcloud components update
        
    # Deploy the Docker image to the Cloud Run
    - name: Cloud Run
      run: |
        gcloud beta run deploy $GCR_SERVICE
        --image $REGISTRY_HOSTNAME/$GCR_PROJECT/$IMAGE:${GITHUB_SHA}
        --region $GCR_ZONE
        --region managed
